/**
 * xrdp: A Remote Desktop Protocol server.
 *
 * Copyright (C) 2026 Tim Pletcher, all xrdp contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Wayland clipboard backend for chansrv: the cliprdr channel ([MS-RDPECLIP])
 * against a Wayland compositor's selection, via ext-data-control-v1, which
 * needs neither a surface nor focus. Text (CF_UNICODETEXT), images
 * (CF_DIB, and the registered "PNG" format Windows browsers and Office
 * use) and files (FileGroupDescriptorW with FileContents streams).
 *
 * Built with --enable-wayland; used instead of the X11 backend (clipboard.c)
 * when chansrv runs with WAYLAND_DISPLAY set. The X11 route through Xwayland
 * does not work under wlroots: its selection bridge only accepts ownership
 * from a focused X client, and chansrv's window is never focused.
 *
 * client -> session: the client's format list makes us the selection owner
 *   (a data source offering text and/or images). When an application
 *   pastes, the source's send event gives us a pipe; we ask the client for
 *   the matching format (one request at a time: responses do not name
 *   their format) and write the answer into every pipe waiting for it.
 *   Images go out as image/bmp (the DIB with a file header) and image/png
 *   (the client's PNG if it has one, else the DIB converted).
 * session -> client: a new selection from anyone else is announced to the
 *   client in the formats we can serve; a data request reads the offer
 *   through a pipe, polled in chansrv's loop, and answers in the client's
 *   format.
 *
 * Files use the X11 backend's machinery (clipboard_file.c): the session's
 * text/uri-list becomes the client's file list, whose contents the client
 * then fetches by FileContents requests; the client's file list becomes
 * files in chansrv's FUSE clipboard directory, offered as text/uri-list and
 * x-special/gnome-copied-files, whose reads become FileContents requests to
 * the client. That direction needs FUSE (--enable-fuse, mounts enabled).
 *
 * RestrictInboundClipboard / RestrictOutboundClipboard apply as in the X11
 * backend: a restricted kind is neither offered nor announced.
 */

#if defined(HAVE_CONFIG_H)
#include <config_ac.h>
#endif

#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <wayland-client.h>
/* generated by wayland-scanner during the build */
/* cppcheck-suppress missingInclude */
#include "ext-data-control-v1-client-protocol.h"

#include "arch.h"
#include "parse.h"
#include "os_calls.h"
#include "string_calls.h"
#include "log.h"
#include "chansrv.h"
#include "chansrv_common.h"
#include "chansrv_config.h"
#include "clipboard_wl.h"
#include "clipboard_wl_image.h"
#include "clipboard_file.h"
#include "ms-rdpeclip.h"
#include "xrdp_constants.h"

extern int g_cliprdr_chan_id; /* in chansrv.c */
extern struct config_chansrv *g_cfg; /* in chansrv.c */
extern char g_fuse_clipboard_path[]; /* in chansrv_fuse.c; "" if unmounted */

#define MAX_WAITING 16
#define MAX_DATA (64 * 1024 * 1024)
/* the id we give the registered "PNG" format in our format lists */
#define PNG_FORMAT_ID 0xC100
/* and the file formats, as the X11 backend numbers them */
#define FILE_GROUP_FORMAT_ID 0xC0BC
#define FILE_CONTENTS_FORMAT_ID 0xC0BA
#define DROP_EFFECT_FORMAT_ID 0xC0C1
#define MAX_FILE_LIST (1024 * 1024)

/* what the clipboard holds, in the terms Wayland applications ask for */
enum kind
{
    K_TEXT,
    K_BMP,
    K_PNG,
    K_URI_LIST,     /* files, text/uri-list */
    K_GNOME_FILES,  /* files, x-special/gnome-copied-files */
    K_COUNT
};

static const char *g_text_mimes[] =
{
    "text/plain;charset=utf-8", "UTF8_STRING", "text/plain", "STRING", "TEXT"
};
static const char *g_bmp_mimes[] =
{
    "image/bmp", "image/x-bmp", "image/x-MS-bmp"
};
static const char g_png_mime[] = "image/png";
static const char g_uri_list_mime[] = "text/uri-list";
static const char g_gnome_files_mime[] = "x-special/gnome-copied-files";
#define NUM_OF(a) (sizeof(a) / sizeof((a)[0]))

/* Offered by our own sources only, so a selection event can be recognised
   as ours whatever order events arrive in (mstsc sends format lists in
   quick succession, which makes "the next selection is ours" unreliable). */
static const char g_own_mime[] = "application/x-xrdp-chansrv-clipboard";

struct offer
{
    struct ext_data_control_offer_v1 *offer;
    int has_utf8;           /* offers text/plain;charset=utf-8 */
    const char *text_mime;  /* a text type to receive, NULL if none */
    const char *bmp_mime;   /* a BMP type, NULL if none */
    int has_png;
    const char *files_mime; /* a file list type, NULL if none */
    int ours;               /* carries g_own_mime: one of our sources */
};

struct c2s_data
{
    char *data;             /* NULL: the client had none, or failed */
    int len;
    int done;               /* fetched (or failed): waiters can have it */
};

struct waiter
{
    int fd;
    enum kind kind;
};

/* what the session is reading for the client */
enum s2c_kind
{
    S_TEXT,
    S_DIB_FROM_BMP,
    S_DIB_FROM_PNG,
    S_PNG,
    S_FILES
};

static int g_up;
static struct wl_display *g_display;
static struct wl_seat *g_seat;
static struct ext_data_control_manager_v1 *g_mgr;
static struct ext_data_control_device_v1 *g_device;
static struct stream *g_ins;            /* reassembly of chunked PDUs */
static int g_long_names = 1;            /* CB_USE_LONG_FORMAT_NAMES agreed */

/* client -> session */
static struct ext_data_control_source_v1 *g_source; /* ours, while we own */
static int g_c2s_png_id;                /* the client's "PNG" format, or 0 */
static int g_c2s_files_id;              /* its "FileGroupDescriptorW", or 0 */
static struct c2s_data g_c2s[K_COUNT];  /* fetched from the client */
static int g_c2s_req_format;            /* request outstanding, or 0 */
static struct waiter g_waiting[MAX_WAITING]; /* pasting applications */
static int g_num_waiting;

/* session -> client */
static struct offer *g_sel;             /* current selection, if not ours */
static int g_s2c_fd = -1;               /* pipe reading g_sel */
static enum s2c_kind g_s2c_kind;
static char *g_s2c_buf;
static int g_s2c_len;
static int g_s2c_size;

/*****************************************************************************/
static int
send_pdu(int msg_type, int msg_flags, const char *data, int len)
{
    struct stream *s;
    int rv;

    make_stream(s);
    init_stream(s, len + 16);
    out_uint16_le(s, msg_type);
    out_uint16_le(s, msg_flags);
    out_uint32_le(s, len);
    if (len > 0)
    {
        out_uint8a(s, data, len);
    }
    out_uint32_le(s, 0); /* the 4 pad bytes the X11 backend also sends */
    s_mark_end(s);
    rv = send_channel_data(g_cliprdr_chan_id, s->data,
                           (int) (s->end - s->data));
    free_stream(s);
    return rv;
}

/*****************************************************************************/
static void
out_format(struct stream *s, int id, const char *name)
{
    int n = (int) strlen(name);
    int i;

    out_uint32_le(s, id);
    if (g_long_names)
    {
        out_utf8_as_utf16_le(s, name, n);
        out_uint16_le(s, 0);
    }
    else
    {
        /* 32 bytes, UTF-16, zero-padded ("PNG" fits) */
        for (i = 0; i < 16; i++)
        {
            out_uint16_le(s, i < n ? (unsigned char) name[i] : 0);
        }
    }
}

/*****************************************************************************/
/* announce what the session's selection can give the client */
static int
send_format_list(int text, int dib, int png, int files)
{
    struct stream *s;
    int rv;

    make_stream(s);
    init_stream(s, 256);
    if (text)
    {
        out_format(s, CF_UNICODETEXT, ""); /* clients synthesise the rest */
    }
    if (dib)
    {
        out_format(s, CF_DIB, "");
    }
    if (png)
    {
        out_format(s, PNG_FORMAT_ID, "PNG");
    }
    if (files)
    {
        /* as the X11 backend announces files */
        out_format(s, FILE_GROUP_FORMAT_ID, "FileGroupDescriptorW");
        out_format(s, FILE_CONTENTS_FORMAT_ID, "FileContents");
        out_format(s, DROP_EFFECT_FORMAT_ID, "DropEffect");
    }
    s_mark_end(s);
    rv = send_pdu(CB_FORMAT_LIST, 0, s->data, (int) (s->end - s->data));
    free_stream(s);
    LOG(LOG_LEVEL_DEBUG, "clipboard_wl: announced text %d dib %d png %d "
        "files %d", text, dib, png, files);
    return rv;
}

/*****************************************************************************/
static int
send_text_response(const char *text, int len)
{
    struct stream *s;
    int words;
    int rv;

    words = utf8_as_utf16_word_count(text, len);
    make_stream(s);
    init_stream(s, words * 2 + 16);
    out_utf8_as_utf16_le(s, text, len);
    out_uint16_le(s, 0);              /* terminator */
    s_mark_end(s);
    rv = send_pdu(CB_FORMAT_DATA_RESPONSE, CB_RESPONSE_OK, s->data,
                  (int) (s->end - s->data));
    free_stream(s);
    return rv;
}

/*****************************************************************************/
static enum kind
mime_kind(const char *mime)
{
    unsigned int i;

    for (i = 0; i < NUM_OF(g_bmp_mimes); i++)
    {
        if (strcmp(mime, g_bmp_mimes[i]) == 0)
        {
            return K_BMP;
        }
    }
    if (strcmp(mime, g_uri_list_mime) == 0)
    {
        return K_URI_LIST;
    }
    if (strcmp(mime, g_gnome_files_mime) == 0)
    {
        return K_GNOME_FILES;
    }
    return strcmp(mime, g_png_mime) == 0 ? K_PNG : K_TEXT;
}

/*****************************************************************************/
static void
write_all(int fd, const char *p, int left)
{
    int flags = fcntl(fd, F_GETFL);

    /* blocking: the application reads as we write */
    fcntl(fd, F_SETFL, flags & ~O_NONBLOCK);
    while (left > 0)
    {
        ssize_t n = write(fd, p, left);

        if (n < 0 && errno == EINTR)
        {
            continue;
        }
        if (n <= 0)
        {
            break;
        }
        p += n;
        left -= n;
    }
}

/*****************************************************************************/
/* pasting applications: hand over what has arrived; with all, close the
   rest empty-handed too */
static void
feed_waiting(int all)
{
    int i;
    int n = 0;

    for (i = 0; i < g_num_waiting; i++)
    {
        struct c2s_data *d = g_c2s + g_waiting[i].kind;

        if (!d->done && !all)
        {
            g_waiting[n++] = g_waiting[i];
            continue;
        }
        if (d->done && d->data != NULL)
        {
            write_all(g_waiting[i].fd, d->data, d->len);
        }
        close(g_waiting[i].fd);
    }
    g_num_waiting = n;
}

/*****************************************************************************/
/* ask the client for the next thing a pasting application waits for */
static void
request_next(void)
{
    struct stream *s;
    int format = 0;
    int i;

    if (g_c2s_req_format != 0)
    {
        return; /* one at a time */
    }
    for (i = 0; i < g_num_waiting && format == 0; i++)
    {
        switch (g_waiting[i].kind)
        {
            case K_TEXT:
                format = CF_UNICODETEXT;
                break;
            case K_BMP:
                format = CF_DIB;
                break;
            case K_URI_LIST:
            case K_GNOME_FILES:
                format = g_c2s_files_id;
                break;
            default:
                format = g_c2s_png_id != 0 ? g_c2s_png_id : CF_DIB;
                break;
        }
    }
    if (format == 0)
    {
        return;
    }
    LOG(LOG_LEVEL_INFO, "clipboard_wl: paste in the session, asking the "
        "client for format 0x%x", format);
    make_stream(s);
    init_stream(s, 16);
    out_uint32_le(s, format);
    s_mark_end(s);
    send_pdu(CB_FORMAT_DATA_REQUEST, 0, s->data, 4);
    free_stream(s);
    g_c2s_req_format = format;
}

/*****************************************************************************/
static void
c2s_reset(void)
{
    int i;

    for (i = 0; i < K_COUNT; i++)
    {
        g_free(g_c2s[i].data);
        g_c2s[i].data = NULL;
        g_c2s[i].len = 0;
        g_c2s[i].done = 0;
    }
    g_c2s_req_format = 0;
}

/*****************************************************************************/
/* our data source */

static void
source_send(void *data, struct ext_data_control_source_v1 *src,
            const char *mime, int32_t fd)
{
    enum kind kind = mime_kind(mime);

    if (src != g_source || g_num_waiting >= MAX_WAITING)
    {
        close(fd);
        return;
    }
    g_waiting[g_num_waiting].fd = fd;
    g_waiting[g_num_waiting].kind = kind;
    g_num_waiting++;
    if (g_c2s[kind].done)
    {
        feed_waiting(0);
        return;
    }
    request_next();
}

static void
source_cancelled(void *data, struct ext_data_control_source_v1 *src)
{
    /* someone else owns the selection now */
    ext_data_control_source_v1_destroy(src);
    if (src == g_source)
    {
        g_source = NULL;
        feed_waiting(1); /* closes the pipes */
    }
}

static const struct ext_data_control_source_v1_listener g_source_listener =
{
    source_send, source_cancelled
};

/*****************************************************************************/
/* offers */

static void
offer_offer(void *data, struct ext_data_control_offer_v1 *o,
            const char *mime)
{
    struct offer *of = data;
    unsigned int i;

    if (strcmp(mime, g_own_mime) == 0)
    {
        of->ours = 1;
        return;
    }
    if (strcmp(mime, g_png_mime) == 0)
    {
        of->has_png = 1;
        return;
    }
    if (strcmp(mime, g_uri_list_mime) == 0 ||
            (strcmp(mime, g_gnome_files_mime) == 0 && of->files_mime == NULL))
    {
        of->files_mime = strcmp(mime, g_uri_list_mime) == 0
                         ? g_uri_list_mime : g_gnome_files_mime;
        return;
    }
    for (i = 0; i < NUM_OF(g_bmp_mimes); i++)
    {
        if (strcmp(mime, g_bmp_mimes[i]) == 0 && of->bmp_mime == NULL)
        {
            of->bmp_mime = g_bmp_mimes[i];
        }
    }
    for (i = 0; i < NUM_OF(g_text_mimes); i++)
    {
        if (strcmp(mime, g_text_mimes[i]) == 0)
        {
            if (i == 0)
            {
                of->has_utf8 = 1;
            }
            if (of->text_mime == NULL)
            {
                of->text_mime = g_text_mimes[i];
            }
        }
    }
}

static const struct ext_data_control_offer_v1_listener g_offer_listener =
{
    offer_offer
};

static void
offer_free(struct offer *of)
{
    if (of != NULL)
    {
        ext_data_control_offer_v1_destroy(of->offer);
        g_free(of);
    }
}

/*****************************************************************************/
static void
s2c_reset_read(void)
{
    if (g_s2c_fd >= 0)
    {
        close(g_s2c_fd);
        g_s2c_fd = -1;
    }
    g_free(g_s2c_buf);
    g_s2c_buf = NULL;
    g_s2c_len = 0;
    g_s2c_size = 0;
}

/*****************************************************************************/
/* device */

static void
device_data_offer(void *data, struct ext_data_control_device_v1 *dev,
                  struct ext_data_control_offer_v1 *o)
{
    struct offer *of = g_new0(struct offer, 1);

    of->offer = o;
    ext_data_control_offer_v1_add_listener(o, &g_offer_listener, of);
}

static void
device_selection(void *data, struct ext_data_control_device_v1 *dev,
                 struct ext_data_control_offer_v1 *o)
{
    struct offer *of = (o != NULL) ? ext_data_control_offer_v1_get_user_data(o)
                       : NULL;
    int text;
    int dib;
    int png;
    int files;

    if (of != NULL && of->ours)
    {
        /* our own source coming back: the client already has it */
        offer_free(of);
        return;
    }
    s2c_reset_read();
    offer_free(g_sel);
    g_sel = NULL;
    if (of == NULL)
    {
        return; /* cleared */
    }
    if (g_cfg->restrict_outbound_clipboard & CLIP_RESTRICT_TEXT)
    {
        of->text_mime = NULL;
    }
    if (g_cfg->restrict_outbound_clipboard & CLIP_RESTRICT_IMAGE)
    {
        of->bmp_mime = NULL;
        of->has_png = 0;
    }
    if (g_cfg->restrict_outbound_clipboard & CLIP_RESTRICT_FILE)
    {
        of->files_mime = NULL;
    }
    if (of->has_utf8 && of->text_mime != NULL)
    {
        of->text_mime = g_text_mimes[0];
    }
    text = of->text_mime != NULL;
    dib = of->bmp_mime != NULL || (of->has_png && wl_image_have_png());
    png = of->has_png;
    files = of->files_mime != NULL;
    if (!text && !dib && !png && !files)
    {
        offer_free(of);
        return;
    }
    g_sel = of;
    LOG(LOG_LEVEL_INFO, "clipboard_wl: session copied%s%s%s%s, announcing "
        "it to the client", text ? " text" : "", dib ? " an image" : "",
        png ? " (PNG)" : "", files ? " files" : "");
    send_format_list(text, dib, png, files);
}

static void
device_finished(void *data, struct ext_data_control_device_v1 *dev)
{
    LOG(LOG_LEVEL_WARNING, "clipboard_wl: data device finished");
    ext_data_control_device_v1_destroy(dev);
    g_device = NULL;
}

static void
device_primary_selection(void *data, struct ext_data_control_device_v1 *dev,
                         struct ext_data_control_offer_v1 *o)
{
    /* RDP has no primary selection */
    if (o != NULL)
    {
        offer_free(ext_data_control_offer_v1_get_user_data(o));
    }
}

static const struct ext_data_control_device_v1_listener g_device_listener =
{
    device_data_offer, device_selection, device_finished,
    device_primary_selection
};

/*****************************************************************************/
static void
registry_global(void *data, struct wl_registry *reg, uint32_t name,
                const char *iface, uint32_t version)
{
    if (g_strcmp(iface, wl_seat_interface.name) == 0 && g_seat == NULL)
    {
        g_seat = wl_registry_bind(reg, name, &wl_seat_interface, 1);
    }
    else if (g_strcmp(iface, ext_data_control_manager_v1_interface.name) == 0)
    {
        g_mgr = wl_registry_bind(reg, name,
                                 &ext_data_control_manager_v1_interface, 1);
    }
}

static void
registry_global_remove(void *data, struct wl_registry *reg, uint32_t name)
{
}

static const struct wl_registry_listener g_registry_listener =
{
    registry_global, registry_global_remove
};

/*****************************************************************************/
int
clipboard_wl_enabled(void)
{
    return g_getenv("WAYLAND_DISPLAY") != NULL;
}

/*****************************************************************************/
int
clipboard_wl_init(void)
{
    struct stream *s;

    if (g_up)
    {
        return 0;
    }
    g_display = wl_display_connect(NULL);
    if (g_display == NULL)
    {
        LOG(LOG_LEVEL_ERROR, "clipboard_wl: cannot connect to the Wayland "
            "display");
        return 1;
    }
    wl_registry_add_listener(wl_display_get_registry(g_display),
                             &g_registry_listener, NULL);
    wl_display_roundtrip(g_display);
    if (g_seat == NULL || g_mgr == NULL)
    {
        LOG(LOG_LEVEL_ERROR, "clipboard_wl: compositor lacks a seat or "
            "ext-data-control-v1");
        wl_display_disconnect(g_display);
        g_display = NULL;
        return 1;
    }
    g_device = ext_data_control_manager_v1_get_data_device(g_mgr, g_seat);
    ext_data_control_device_v1_add_listener(g_device, &g_device_listener,
                                            NULL);
    make_stream(g_ins);
    init_stream(g_ins, 8192);

    /* caps, then monitor ready, as the X11 backend does */
    make_stream(s);
    init_stream(s, 64);
    out_uint16_le(s, 1);                        /* cCapabilitiesSets */
    out_uint16_le(s, 0);                        /* pad */
    out_uint16_le(s, CB_CAPSTYPE_GENERAL);
    out_uint16_le(s, 12);
    out_uint32_le(s, CB_CAPS_VERSION_2);
    out_uint32_le(s, CB_USE_LONG_FORMAT_NAMES | CB_STREAM_FILECLIP_ENABLED |
                  CB_FILECLIP_NO_FILE_PATHS);
    s_mark_end(s);
    send_pdu(CB_CLIP_CAPS, 0, s->data, (int) (s->end - s->data));
    free_stream(s);
    send_pdu(CB_MONITOR_READY, 0, NULL, 0);
    g_up = 1;

    /* the current selection, announced to the client if we can serve it */
    wl_display_roundtrip(g_display);
    LOG(LOG_LEVEL_INFO, "clipboard_wl: up (ext-data-control), images %s",
        wl_image_have_png() ? "BMP and PNG" : "BMP only (built without "
        "libpng)");
    return 0;
}

/*****************************************************************************/
int
clipboard_wl_deinit(void)
{
    if (!g_up)
    {
        return 0;
    }
    s2c_reset_read();
    offer_free(g_sel);
    g_sel = NULL;
    feed_waiting(1);
    c2s_reset();
    if (g_source != NULL)
    {
        ext_data_control_source_v1_destroy(g_source);
        g_source = NULL;
    }
    if (g_device != NULL)
    {
        ext_data_control_device_v1_destroy(g_device);
        g_device = NULL;
    }
    wl_display_disconnect(g_display);
    g_display = NULL;
    g_seat = NULL;
    g_mgr = NULL;
    free_stream(g_ins);
    g_ins = NULL;
    g_up = 0;
    return 0;
}

/*****************************************************************************/
/* a short (32-byte) format name is "PNG", in ASCII or UTF-16 */
static int
short_name_is_png(const char *p, int ascii)
{
    if (ascii)
    {
        return memcmp(p, "PNG", 4) == 0;
    }
    return memcmp(p, "P\0N\0G\0\0\0", 8) == 0;
}

/*****************************************************************************/
/* client's format list: take the selection if it has what we offer */
static void
process_format_list(struct stream *s, int flags, int len)
{
    int has_text = 0;
    int has_dib = 0;
    int png_id = 0;
    int files_id = 0;
    int id;
    char name[256];
    unsigned int i;

    while (len >= 4 && s_check_rem(s, 4))
    {
        char *start = s->p;

        in_uint32_le(s, id);
        name[0] = '\0';
        if (g_long_names)
        {
            in_utf16_le_terminated_as_utf8(s, name, sizeof(name));
        }
        else if (s_check_rem(s, 32))
        {
            if (short_name_is_png(s->p, flags & CB_ASCII_NAMES))
            {
                g_strcpy(name, "PNG");
            }
            in_uint8s(s, 32);
        }
        len -= (int) (s->p - start);
        if (id == CF_UNICODETEXT || id == CF_TEXT)
        {
            has_text = 1;
        }
        else if (id == CF_DIB)
        {
            has_dib = 1;
        }
        else if (g_strcmp(name, "PNG") == 0)
        {
            png_id = id;
        }
        else if (g_strcmp(name, "FileGroupDescriptorW") == 0)
        {
            files_id = id;
        }
    }
    send_pdu(CB_FORMAT_LIST_RESPONSE, CB_RESPONSE_OK, NULL, 0);

    if (g_cfg->restrict_inbound_clipboard & CLIP_RESTRICT_TEXT)
    {
        has_text = 0;
    }
    if (g_cfg->restrict_inbound_clipboard & CLIP_RESTRICT_IMAGE)
    {
        has_dib = 0;
        png_id = 0;
    }
    if ((g_cfg->restrict_inbound_clipboard & CLIP_RESTRICT_FILE) ||
            g_fuse_clipboard_path[0] == '\0')
    {
        /* the client's files only exist for us through FUSE */
        if (files_id != 0 && g_fuse_clipboard_path[0] == '\0')
        {
            LOG(LOG_LEVEL_INFO, "clipboard_wl: the client copied files, but "
                "there is no FUSE clipboard directory to put them in");
        }
        files_id = 0;
    }

    /* a new client clipboard: forget the old one */
    feed_waiting(1);
    c2s_reset();
    g_c2s_png_id = png_id;
    g_c2s_files_id = files_id;
    if (g_source != NULL)
    {
        ext_data_control_source_v1_destroy(g_source);
        g_source = NULL;
    }
    if (!has_text && !has_dib && png_id == 0 && files_id == 0)
    {
        return;
    }
    g_source = ext_data_control_manager_v1_create_data_source(g_mgr);
    if (has_text)
    {
        for (i = 0; i < NUM_OF(g_text_mimes); i++)
        {
            ext_data_control_source_v1_offer(g_source, g_text_mimes[i]);
        }
    }
    if (png_id != 0 || (has_dib && wl_image_have_png()))
    {
        /* first: applications take the first image type they know */
        ext_data_control_source_v1_offer(g_source, g_png_mime);
    }
    if (has_dib)
    {
        for (i = 0; i < NUM_OF(g_bmp_mimes); i++)
        {
            ext_data_control_source_v1_offer(g_source, g_bmp_mimes[i]);
        }
    }
    if (files_id != 0)
    {
        ext_data_control_source_v1_offer(g_source, g_gnome_files_mime);
        ext_data_control_source_v1_offer(g_source, g_uri_list_mime);
    }
    ext_data_control_source_v1_offer(g_source, g_own_mime);
    ext_data_control_source_v1_add_listener(g_source, &g_source_listener,
                                            NULL);
    ext_data_control_device_v1_set_selection(g_device, g_source);
    wl_display_flush(g_display);
    LOG(LOG_LEVEL_INFO, "clipboard_wl: client copied%s%s%s%s, owning the "
        "selection", has_text ? " text" : "", has_dib ? " an image" : "",
        png_id != 0 ? " (PNG)" : "", files_id != 0 ? " files" : "");
}

/*****************************************************************************/
/* the client wants the session's selection: read the offer through a pipe */
static void
process_data_request(struct stream *s)
{
    const char *mime = NULL;
    int id;
    int fds[2];

    in_uint32_le(s, id);
    if (g_sel != NULL)
    {
        if (id == CF_UNICODETEXT && g_sel->text_mime != NULL)
        {
            mime = g_sel->text_mime;
            g_s2c_kind = S_TEXT;
        }
        else if (id == CF_DIB && g_sel->bmp_mime != NULL)
        {
            mime = g_sel->bmp_mime;
            g_s2c_kind = S_DIB_FROM_BMP;
        }
        else if (id == CF_DIB && g_sel->has_png && wl_image_have_png())
        {
            mime = g_png_mime;
            g_s2c_kind = S_DIB_FROM_PNG;
        }
        else if (id == PNG_FORMAT_ID && g_sel->has_png)
        {
            mime = g_png_mime;
            g_s2c_kind = S_PNG;
        }
        else if (id == FILE_GROUP_FORMAT_ID && g_sel->files_mime != NULL)
        {
            mime = g_sel->files_mime;
            g_s2c_kind = S_FILES;
        }
        else if (id == DROP_EFFECT_FORMAT_ID && g_sel->files_mime != NULL)
        {
            /* a copy, never a move */
            const char effect[4] = { 1, 0, 0, 0 }; /* DROPEFFECT_COPY */

            send_pdu(CB_FORMAT_DATA_RESPONSE, CB_RESPONSE_OK, effect, 4);
            return;
        }
    }
    s2c_reset_read();
    if (mime == NULL || pipe2(fds, O_CLOEXEC) != 0)
    {
        send_pdu(CB_FORMAT_DATA_RESPONSE, CB_RESPONSE_FAIL, NULL, 0);
        return;
    }
    ext_data_control_offer_v1_receive(g_sel->offer, mime, fds[1]);
    wl_display_flush(g_display);
    close(fds[1]);
    fcntl(fds[0], F_SETFL, O_NONBLOCK);
    g_s2c_fd = fds[0];
    g_s2c_size = 4096;
    g_s2c_buf = g_new(char, g_s2c_size);
}

/*****************************************************************************/
/* a file path as a file:// URI: RFC 3986 unreserved characters and '/'
   as they are, every other byte %-encoded */
static int
out_file_uri(char *out, int size, const char *path)
{
    static const char hex[] = "0123456789ABCDEF";
    int n = g_snprintf(out, size, "file://");

    for (; *path != '\0' && n + 4 < size; path++)
    {
        unsigned char c = (unsigned char) path[0];

        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                (c >= '0' && c <= '9') || strchr("-._~/", c) != NULL)
        {
            out[n++] = c;
        }
        else
        {
            out[n++] = '%';
            out[n++] = hex[c >> 4];
            out[n++] = hex[c & 15];
        }
    }
    out[n] = '\0';
    return n;
}

/*****************************************************************************/
/* The client's file list: its files go into the FUSE clipboard directory
   (clipboard_c2s_in_files), and the session gets their paths as
   text/uri-list and x-special/gnome-copied-files. */
static void
c2s_files(struct stream *s, int ok)
{
    char *paths = NULL;
    char *uris = NULL;
    char *gnome = NULL;
    int uris_len = 0;
    int count = 0;

    if (ok)
    {
        paths = g_new(char, MAX_FILE_LIST);
        uris = g_new(char, MAX_FILE_LIST * 3 + 16);
    }
    if (paths != NULL && uris != NULL &&
            clipboard_c2s_in_files(s, paths, MAX_FILE_LIST, "") == 0)
    {
        char *line = paths;

        /* one absolute path per line */
        while (*line != '\0')
        {
            char *end = strchr(line, '\n');
            char uri[4096];

            if (end != NULL)
            {
                *end = '\0';
            }
            if (*line != '\0')
            {
                int n = out_file_uri(uri, sizeof(uri), line);

                if (uris_len + n + 3 < MAX_FILE_LIST * 3 + 16)
                {
                    memcpy(uris + uris_len, uri, n);
                    uris_len += n;
                    uris[uris_len++] = '\r'; /* RFC 2483 line ends */
                    uris[uris_len++] = '\n';
                    count++;
                }
            }
            if (end == NULL)
            {
                break;
            }
            line = end + 1;
        }
    }
    if (count > 0)
    {
        /* "copy", then the URIs one per line */
        int i;
        int j = 0;

        gnome = g_new(char, uris_len + 8);
        if (gnome != NULL)
        {
            g_strcpy(gnome, "copy\n");
            j = 5;
            for (i = 0; i < uris_len; i++)
            {
                if (uris[i] != '\r')
                {
                    gnome[j++] = uris[i];
                }
            }
            /* no line end after the last one */
            if (j > 5 && gnome[j - 1] == '\n')
            {
                j--;
            }
            g_c2s[K_GNOME_FILES].data = gnome;
            g_c2s[K_GNOME_FILES].len = j;
        }
        g_c2s[K_URI_LIST].data = uris;
        g_c2s[K_URI_LIST].len = uris_len;
        uris = NULL;
    }
    g_c2s[K_URI_LIST].done = 1;
    g_c2s[K_GNOME_FILES].done = 1;
    LOG(LOG_LEVEL_INFO, "clipboard_wl: %d client file(s) in %s", count,
        g_fuse_clipboard_path);
    g_free(paths);
    g_free(uris);
}

/*****************************************************************************/
/* the client's data arrived: it answers the request outstanding */
static void
process_data_response(struct stream *s, int flags, int len)
{
    int format = g_c2s_req_format;
    int ok = flags == CB_RESPONSE_OK;
    char *out = NULL;
    int out_len = 0;
    int bytes;

    g_c2s_req_format = 0;
    bytes = len < s_rem(s) ? len : s_rem(s);
    if (format == CF_UNICODETEXT)
    {
        struct c2s_data *d = g_c2s + K_TEXT;

        if (ok && bytes >= 2)
        {
            unsigned int n = in_utf16_le_terminated_as_utf8_length(s);

            d->data = g_new(char, n);
            if (d->data != NULL)
            {
                in_utf16_le_terminated_as_utf8(s, d->data, n);
                d->len = (int) n - 1; /* no terminator */
            }
        }
        d->done = 1;
    }
    else if (format == CF_DIB)
    {
        /* one DIB serves both image types */
        if (ok && wl_image_dib_to_bmp(s->p, bytes, &out, &out_len) == 0)
        {
            g_c2s[K_BMP].data = out;
            g_c2s[K_BMP].len = out_len;
        }
        g_c2s[K_BMP].done = 1;
        if (g_c2s_png_id == 0)
        {
            if (ok && wl_image_dib_to_png(s->p, bytes, &out, &out_len) == 0)
            {
                g_c2s[K_PNG].data = out;
                g_c2s[K_PNG].len = out_len;
            }
            g_c2s[K_PNG].done = 1;
        }
    }
    else if (format != 0 && format == g_c2s_files_id)
    {
        c2s_files(s, ok);
    }
    else if (format != 0 && format == g_c2s_png_id)
    {
        if (ok && bytes > 0)
        {
            g_c2s[K_PNG].data = g_new(char, bytes);
            if (g_c2s[K_PNG].data != NULL)
            {
                memcpy(g_c2s[K_PNG].data, s->p, bytes);
                g_c2s[K_PNG].len = bytes;
            }
        }
        g_c2s[K_PNG].done = 1;
    }
    else
    {
        return; /* not ours to answer (a stale response) */
    }
    LOG(LOG_LEVEL_INFO, "clipboard_wl: client format 0x%x, %d bytes%s",
        format, bytes, ok ? "" : " (failed)");
    feed_waiting(0);
    request_next();
}

/*****************************************************************************/
static void
process_caps(struct stream *s)
{
    int sets;
    int i;

    in_uint16_le(s, sets);
    in_uint8s(s, 2);
    for (i = 0; i < sets && s_check_rem(s, 4); i++)
    {
        char *hold = s->p;
        int type;
        int len;

        in_uint16_le(s, type);
        in_uint16_le(s, len);
        if (type == CB_CAPSTYPE_GENERAL && s_check_rem(s, 8))
        {
            int version;
            int flags;

            in_uint32_le(s, version);
            in_uint32_le(s, flags);
            g_long_names = (flags & CB_USE_LONG_FORMAT_NAMES) != 0;
            (void) version;
        }
        s->p = hold + len;
    }
}

/*****************************************************************************/
int
clipboard_wl_data_in(struct stream *s, int chan_id, int chan_flags,
                     int length, int total_length)
{
    struct stream *ls;
    int msg_type;
    int msg_flags;
    int msg_len;

    if (!g_up)
    {
        return 0;
    }
    if ((chan_flags & 3) == 3)
    {
        ls = s;
    }
    else
    {
        if (chan_flags & 1)
        {
            init_stream(g_ins, total_length);
        }
        in_uint8a(s, g_ins->end, length);
        g_ins->end += length;
        if ((chan_flags & 2) == 0)
        {
            return 0;
        }
        ls = g_ins;
    }
    if (!s_check_rem(ls, 8))
    {
        return 0;
    }
    in_uint16_le(ls, msg_type);
    in_uint16_le(ls, msg_flags);
    in_uint32_le(ls, msg_len);
    switch (msg_type)
    {
        case CB_CLIP_CAPS:
            process_caps(ls);
            break;
        case CB_FORMAT_LIST:
            process_format_list(ls, msg_flags, msg_len);
            break;
        case CB_FORMAT_DATA_REQUEST:
            process_data_request(ls);
            break;
        case CB_FORMAT_DATA_RESPONSE:
            process_data_response(ls, msg_flags, msg_len);
            break;
        case CB_FILECONTENTS_REQUEST:
            clipboard_process_file_request(ls, msg_flags, msg_len);
            break;
        case CB_FILECONTENTS_RESPONSE:
            clipboard_process_file_response(ls, msg_flags, msg_len);
            break;
        default:
            break;
    }
    if (g_display != NULL)
    {
        wl_display_flush(g_display);
    }
    return 0;
}

/*****************************************************************************/
int
clipboard_wl_get_wait_objs(tbus *objs, int *count, int *timeout)
{
    if (!g_up || g_display == NULL)
    {
        return 0;
    }
    wl_display_flush(g_display);
    objs[(*count)++] = wl_display_get_fd(g_display);
    if (g_s2c_fd >= 0)
    {
        objs[(*count)++] = g_s2c_fd;
    }
    return 0;
}

/*****************************************************************************/
/* the session's data, converted for the client */
static void
s2c_send(void)
{
    char *out = NULL;
    int out_len = 0;
    int rv = 1;

    switch (g_s2c_kind)
    {
        case S_TEXT:
            send_text_response(g_s2c_buf, g_s2c_len);
            return;
        case S_DIB_FROM_BMP:
            rv = wl_image_bmp_to_dib(g_s2c_buf, g_s2c_len, &out, &out_len);
            break;
        case S_DIB_FROM_PNG:
            rv = wl_image_png_to_dib(g_s2c_buf, g_s2c_len, &out, &out_len);
            break;
        case S_PNG:
            send_pdu(CB_FORMAT_DATA_RESPONSE,
                     g_s2c_len > 0 ? CB_RESPONSE_OK : CB_RESPONSE_FAIL,
                     g_s2c_buf, g_s2c_len);
            return;
        case S_FILES:
            /* the file list; the client then asks for the contents */
            clipboard_send_data_response_for_file(g_s2c_buf, g_s2c_len);
            return;
    }
    if (rv != 0)
    {
        LOG(LOG_LEVEL_WARNING, "clipboard_wl: the session's image (%d bytes) "
            "could not be converted", g_s2c_len);
        send_pdu(CB_FORMAT_DATA_RESPONSE, CB_RESPONSE_FAIL, NULL, 0);
        return;
    }
    send_pdu(CB_FORMAT_DATA_RESPONSE, CB_RESPONSE_OK, out, out_len);
    free(out);
}

/*****************************************************************************/
/* the session's data, read so far; EOF sends it */
static void
s2c_read(void)
{
    for (;;)
    {
        ssize_t n;

        if (g_s2c_len == g_s2c_size)
        {
            char *p;

            if (g_s2c_size >= MAX_DATA)
            {
                break;
            }
            p = (char *) realloc(g_s2c_buf, g_s2c_size * 2);
            if (p == NULL)
            {
                break;
            }
            g_s2c_buf = p;
            g_s2c_size *= 2;
        }
        n = read(g_s2c_fd, g_s2c_buf + g_s2c_len, g_s2c_size - g_s2c_len);
        if (n > 0)
        {
            g_s2c_len += n;
            continue;
        }
        if (n < 0 && (errno == EAGAIN || errno == EINTR))
        {
            return; /* more to come */
        }
        break; /* EOF or error */
    }
    LOG(LOG_LEVEL_DEBUG, "clipboard_wl: session data %d bytes", g_s2c_len);
    s2c_send();
    s2c_reset_read();
}

/*****************************************************************************/
int
clipboard_wl_check_wait_objs(void)
{
    struct pollfd pfd;

    if (!g_up || g_display == NULL)
    {
        return 0;
    }
    pfd.fd = wl_display_get_fd(g_display);
    pfd.events = POLLIN;
    pfd.revents = 0;
    if (poll(&pfd, 1, 0) > 0)
    {
        if (wl_display_dispatch(g_display) < 0)
        {
            LOG(LOG_LEVEL_ERROR, "clipboard_wl: Wayland connection lost");
            clipboard_wl_deinit();
            return 0;
        }
    }
    else
    {
        wl_display_dispatch_pending(g_display);
    }
    if (g_s2c_fd >= 0)
    {
        pfd.fd = g_s2c_fd;
        pfd.events = POLLIN;
        pfd.revents = 0;
        if (poll(&pfd, 1, 0) > 0)
        {
            s2c_read();
        }
    }
    wl_display_flush(g_display);
    return 0;
}
