/**
 * xrdp: A Remote Desktop Protocol server.
 *
 * Copyright (C) 2026 Tim Pletcher, all xrdp contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * wla_wlr: wlxrdp's adapter for wlroots compositors (labwc, sway, Wayfire…),
 * through standard Wayland protocols (wla.h is the interface):
 *
 *   - monitors: the compositor's headless outputs, enabled, sized and placed
 *     with wlr-output-management;
 *   - capture: ext-image-copy-capture of each output, into GBM dma-bufs (GPU
 *     path) or wl_shm buffers (CPU path);
 *   - cursor: a pointer cursor session per output;
 *   - input: zwp_virtual_keyboard_v1 (with the core's keymap) and
 *     zwlr_virtual_pointer_v1.
 */

#include <config_ac.h>

#include <errno.h>
#include <fcntl.h>
#include <math.h>
#include <poll.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <sys/mman.h>

#include <gbm.h>
#include <drm_fourcc.h>
#include <wayland-client.h>

/* generated by wayland-scanner during the build */
/* cppcheck-suppress-begin missingInclude */
#include "ext-image-capture-source-v1-client-protocol.h"
#include "ext-image-copy-capture-v1-client-protocol.h"
#include "linux-dmabuf-v1-client-protocol.h"
#include "wlr-virtual-pointer-unstable-v1-client-protocol.h"
#include "virtual-keyboard-unstable-v1-client-protocol.h"
#include "wlr-output-management-unstable-v1-client-protocol.h"
/* cppcheck-suppress-end missingInclude */

#include "arch.h"
#include "os_calls.h"
#include "log.h"
#include "wla.h"

/* capture buffers per monitor: the core holds the newest (full-frame
   repaints) and any whose frame the helper may still be reading; capture
   goes into a free one */
#define NUM_BUFS 3
#define MAX_RECTS 256
/* outputs we can drive: the compositor's headless outputs, at most */
#define MAX_MONS WLA_MAX_MONITORS
/* a new capture session delivers its first frame at once; none by then
   means it is stuck, so start another */
#define FIRST_FRAME_MS 2000
/* a capture that does not restart is retried this often, this many times,
   before the compositor is given up on (wlxrdp ends; sesexec restarts it) */
#define CAPTURE_RETRY_MS 1000
#define CAPTURE_RETRIES 5

struct buf
{
    struct gbm_bo *bo;
    struct wl_buffer *wl_buffer;
    int fd;
    uint32_t stride;
    uint32_t offset;
    uint64_t modifier;
    /* CPU path: a wl_shm buffer instead of a dma-buf */
    uint8_t *shm;
    int shm_stride;
    size_t shm_bytes;
    int held;                   /* the core has it: not to capture into */
};

struct wlr;

/* one output's cursor: its own capture session, into a small shm buffer */
struct cursor
{
    struct ext_image_copy_capture_cursor_session_v1 *csession;
    struct ext_image_copy_capture_session_v1 *session;
    struct ext_image_copy_capture_frame_v1 *frame;
    int width;                  /* buffer constraints */
    int height;
    int have_argb;
    int constraints_done;
    int stopped;
    struct wl_buffer *buffer;
    void *data;
    int buf_w;
    int buf_h;
    int frame_state;            /* 0 none, 1 pending, 2 ready, 3 failed */
    int hot_x;
    int hot_y;
    int entered;                /* the pointer is on this output */
    uint32_t *image;            /* last captured image, buf_w x buf_h */
    int have_image;
    /* A hotspot change waits (briefly) for its image, so the client never
       gets the new hotspot on the old shape. */
    int hot_pending;
    uint32_t hot_ms;
};

/* one monitor: a compositor output (head) and its capture */
struct wlr_mon
{
    struct wlr *b;
    int index;                  /* the core's monitor number */
    char name[64];              /* the head's (and wl_output's) name */
    struct zwlr_output_head_v1 *head;
    struct wl_output *output;   /* only while the output is enabled */
    uint32_t output_global;
    int enabled;                /* in the client's layout */
    int x;                      /* its place and size in the layout */
    int y;
    int want_w;
    int want_h;
    int scale;                  /* percent */
    int lx;                     /* its place and size in the compositor's */
    int ly;                     /* logical (scaled) coordinates */
    int lw;
    int lh;

    /* capture session */
    struct ext_image_copy_capture_session_v1 *session;
    struct ext_image_copy_capture_frame_v1 *frame;
    int width;
    int height;
    int have_xrgb;
    uint32_t shm_format;        /* CPU path: XRGB8888, else XBGR8888; 0 none */
    uint64_t *mods;
    int num_mods;
    int constraints_done;
    int stopped;
    struct buf bufs[NUM_BUFS];
    int alloc_w;                /* size the capture buffers have */
    int alloc_h;
    int constraints_changed;    /* the compositor changed the buffer size */
    uint32_t capture_ms;        /* when this capture session started */
    uint32_t request_ms;        /* when the pending frame was requested */
    int wanted;                 /* the core wants a frame */
    int retries;                /* failed capture restarts in a row */
    uint32_t retry_ms;          /* when the last one failed */
    int cur;                    /* buffer the pending frame captures into */
    int last_ready;             /* newest complete buffer, -1 if none */
    struct xh_rect rects[MAX_RECTS];
    int num_rects;
    int frame_state;            /* 0 none, 1 pending, 2 ready, 3 failed */

    struct cursor cur_ptr;
};

/* the adapter */
struct wlr
{
    const struct wla_events *ev;
    void *core;

    struct wl_display *display;
    struct wl_seat *seat;
    struct wl_pointer *pointer;
    struct wl_shm *shm;
    struct ext_output_image_capture_source_manager_v1 *source_mgr;
    struct ext_image_copy_capture_manager_v1 *copy_mgr;
    struct zwp_linux_dmabuf_v1 *dmabuf;
    struct zwlr_virtual_pointer_manager_v1 *vptr_mgr;
    struct zwp_virtual_keyboard_manager_v1 *vkbd_mgr;
    struct zwlr_virtual_pointer_v1 *vptr;
    struct zwp_virtual_keyboard_v1 *vkbd;
    struct zwlr_output_manager_v1 *om_mgr;
    uint32_t om_serial;

    /* monitors, in head order */
    struct wlr_mon mons[MAX_MONS];
    int num_mons;               /* heads found */
    int active;                 /* monitors in the layout */

    /* GBM only allocates the capture buffers; encoding is the helper's */
    int drm_fd;
    struct gbm_device *gbm;
    int wl_shm;                 /* capture into shm (the CPU path) */
    int cursor_dirty;           /* an image or hotspot came */
    int capturing;              /* between start and stop */
};

static int capture_start_all(struct wlr *b);
static void capture_stop_all(struct wlr *b);
static void cursor_request(struct wlr_mon *m);
static void wlr_destroy(void *a);

/*****************************************************************************/
static uint32_t
now_ms32(void)
{
    struct timespec ts;

    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint32_t) (ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}



/*****************************************************************************/
/* monitors by name: output-management heads create them; wl_outputs,
   which exist only while an output is enabled, attach to them */
static struct wlr_mon *
mon_by_name(struct wlr *b, const char *name, int create)
{
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        if (strcmp(b->mons[i].name, name) == 0)
        {
            return b->mons + i;
        }
    }
    if (!create || b->num_mons >= MAX_MONS)
    {
        return NULL;
    }
    i = b->num_mons++;
    snprintf(b->mons[i].name, sizeof(b->mons[i].name), "%s", name);
    return b->mons + i;
}

/*****************************************************************************/
/* Wayland outputs */

struct output_ref
{
    struct wlr *b;
    struct wl_output *output;
    uint32_t global;
};

static void
output_geometry(void *data, struct wl_output *o, int32_t x, int32_t y,
                int32_t pw, int32_t ph, int32_t subpixel, const char *make,
                const char *model, int32_t transform)
{
}

static void
output_mode(void *data, struct wl_output *o, uint32_t flags, int32_t w,
            int32_t h, int32_t refresh)
{
}

static void
output_done(void *data, struct wl_output *o)
{
}

static void
output_scale(void *data, struct wl_output *o, int32_t factor)
{
}

static void
output_name(void *data, struct wl_output *o, const char *name)
{
    struct output_ref *ref = data;
    struct wlr_mon *m = mon_by_name(ref->b, name, 1);

    if (m != NULL)
    {
        m->output = ref->output;
        m->output_global = ref->global;
    }
}

static void
output_description(void *data, struct wl_output *o, const char *desc)
{
}

static const struct wl_output_listener g_output_listener =
{
    output_geometry, output_mode, output_done, output_scale,
    output_name, output_description
};

/*****************************************************************************/
/* output management (wlr-output-management): the monitor layout */

static void
om_mode_size(void *data, struct zwlr_output_mode_v1 *m, int32_t w, int32_t h)
{
}

static void
om_mode_refresh(void *data, struct zwlr_output_mode_v1 *m, int32_t r)
{
}

static void
om_mode_preferred(void *data, struct zwlr_output_mode_v1 *m)
{
}

static void
om_mode_finished(void *data, struct zwlr_output_mode_v1 *m)
{
    zwlr_output_mode_v1_destroy(m);
}

static const struct zwlr_output_mode_v1_listener g_om_mode_listener =
{
    om_mode_size, om_mode_refresh, om_mode_preferred, om_mode_finished
};

static void
om_head_name(void *data, struct zwlr_output_head_v1 *h, const char *name)
{
    struct wlr *b = data;
    struct wlr_mon *m = mon_by_name(b, name, 1);

    if (m != NULL)
    {
        m->head = h;
    }
}

static void
om_head_description(void *data, struct zwlr_output_head_v1 *h,
                    const char *d)
{
}

static void
om_head_physical_size(void *data, struct zwlr_output_head_v1 *h,
                      int32_t w, int32_t hh)
{
}

static void
om_head_mode(void *data, struct zwlr_output_head_v1 *h,
             struct zwlr_output_mode_v1 *m)
{
    zwlr_output_mode_v1_add_listener(m, &g_om_mode_listener, data);
}

static void
om_head_enabled(void *data, struct zwlr_output_head_v1 *h, int32_t e)
{
}

static void
om_head_current_mode(void *data, struct zwlr_output_head_v1 *h,
                     struct zwlr_output_mode_v1 *m)
{
}

static void
om_head_position(void *data, struct zwlr_output_head_v1 *h,
                 int32_t x, int32_t y)
{
}

static void
om_head_transform(void *data, struct zwlr_output_head_v1 *h, int32_t t)
{
}

static void
om_head_scale(void *data, struct zwlr_output_head_v1 *h, wl_fixed_t s)
{
}

static void
om_head_finished(void *data, struct zwlr_output_head_v1 *h)
{
    struct wlr *b = data;
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        if (b->mons[i].head == h)
        {
            b->mons[i].head = NULL;
        }
    }
    zwlr_output_head_v1_destroy(h);
}

static void
om_head_string(void *data, struct zwlr_output_head_v1 *h, const char *s)
{
}

static void
om_head_adaptive_sync(void *data, struct zwlr_output_head_v1 *h,
                      uint32_t state)
{
}

static const struct zwlr_output_head_v1_listener g_om_head_listener =
{
    om_head_name, om_head_description, om_head_physical_size, om_head_mode,
    om_head_enabled, om_head_current_mode, om_head_position,
    om_head_transform, om_head_scale, om_head_finished,
    om_head_string, om_head_string, om_head_string, om_head_adaptive_sync
};

static void
om_manager_head(void *data, struct zwlr_output_manager_v1 *m,
                struct zwlr_output_head_v1 *h)
{
    zwlr_output_head_v1_add_listener(h, &g_om_head_listener, data);
}

static void
om_manager_done(void *data, struct zwlr_output_manager_v1 *m,
                uint32_t serial)
{
    struct wlr *b = data;

    b->om_serial = serial;
}

static void
om_manager_finished(void *data, struct zwlr_output_manager_v1 *m)
{
}

static const struct zwlr_output_manager_v1_listener g_om_manager_listener =
{
    om_manager_head, om_manager_done, om_manager_finished
};

static void
om_config_succeeded(void *data, struct zwlr_output_configuration_v1 *c)
{
    *(int *) data = 1;
}

static void
om_config_failed(void *data, struct zwlr_output_configuration_v1 *c)
{
    *(int *) data = -1;
}

static void
om_config_cancelled(void *data, struct zwlr_output_configuration_v1 *c)
{
    *(int *) data = -2;
}

static const struct zwlr_output_configuration_v1_listener
    g_om_config_listener =
{
    om_config_succeeded, om_config_failed, om_config_cancelled
};

/*****************************************************************************/
/* Apply the monitors' layout (enabled, place, size) in one configuration:
   the first b->active monitors on, the rest off. Returns 0 once the
   compositor has applied it; retried once on an out-of-date serial. */
static int
layout_apply(struct wlr *b)
{
    int attempt;
    int i;

    if (b->om_mgr == NULL)
    {
        LOG(LOG_LEVEL_ERROR, "layout: no output management");
        return 1;
    }
    for (attempt = 0; attempt < 2; attempt++)
    {
        struct zwlr_output_configuration_v1 *cfg;
        int result = 0;

        cfg = zwlr_output_manager_v1_create_configuration(b->om_mgr,
              b->om_serial);
        zwlr_output_configuration_v1_add_listener(cfg, &g_om_config_listener,
                &result);
        for (i = 0; i < b->num_mons; i++)
        {
            struct wlr_mon *m = b->mons + i;

            if (m->head == NULL)
            {
                continue;
            }
            if (m->enabled)
            {
                struct zwlr_output_configuration_head_v1 *ch;

                ch = zwlr_output_configuration_v1_enable_head(cfg, m->head);
                zwlr_output_configuration_head_v1_set_custom_mode(
                    ch, m->want_w, m->want_h, 60000);
                zwlr_output_configuration_head_v1_set_position(ch, m->lx,
                        m->ly);
                zwlr_output_configuration_head_v1_set_scale(
                    ch, wl_fixed_from_double(m->scale / 100.0));
            }
            else
            {
                zwlr_output_configuration_v1_disable_head(cfg, m->head);
            }
        }
        zwlr_output_configuration_v1_apply(cfg);
        while (result == 0)
        {
            if (wl_display_dispatch(b->display) < 0)
            {
                return 1;
            }
        }
        zwlr_output_configuration_v1_destroy(cfg);
        if (result == 1)
        {
            /* enabled outputs get (new) wl_output globals: bind them */
            wl_display_roundtrip(b->display);
            wl_display_roundtrip(b->display);
            for (i = 0; i < b->num_mons; i++)
            {
                struct wlr_mon *m = b->mons + i;

                if (m->enabled)
                {
                    LOG(LOG_LEVEL_INFO, "monitor %d: %s %dx%d at %d,%d, "
                        "scale %d%% (logical %dx%d at %d,%d)", m->index,
                        m->name, m->want_w, m->want_h, m->x, m->y, m->scale,
                        m->lw, m->lh, m->lx, m->ly);
                }
            }
            return 0;
        }
        if (result == -1)
        {
            break;
        }
        wl_display_roundtrip(b->display); /* cancelled: pick up the serial */
    }
    LOG(LOG_LEVEL_ERROR, "layout of %d monitor(s) failed", b->active);
    return 1;
}

/* the wlroots adapter: one monitor per headless output */
static int
wlr_max_monitors(void *a)
{
    struct wlr *b = a;

    return b->num_mons;
}

/* Monitor i's place in logical coordinates. With one scale, the layout
   shrinks as a whole. With several, a monitor keeps touching the one it
   touched in the client's layout: its logical place follows its left (or
   upper) neighbour's logical edge, else its pixel place at its own scale. */
static void
layout_logical(struct wlr *b, int n)
{
    int uniform = 1;
    int pass;
    int i;
    int j;

    for (i = 0; i < n; i++)
    {
        struct wlr_mon *m = b->mons + i;
        double s = m->scale / 100.0;

        m->lw = (int) lround(m->want_w / s);
        m->lh = (int) lround(m->want_h / s);
        m->lx = (int) lround(m->x / s);
        m->ly = (int) lround(m->y / s);
        uniform = uniform && m->scale == b->mons[0].scale;
    }
    if (uniform)
    {
        return;
    }
    /* neighbours first: n passes settle any chain of n monitors */
    for (pass = 0; pass < n; pass++)
    {
        for (i = 0; i < n; i++)
        {
            struct wlr_mon *m = b->mons + i;

            for (j = 0; j < n; j++)
            {
                struct wlr_mon *o = b->mons + j;

                if (j == i)
                {
                    continue;
                }
                if (o->x + o->want_w == m->x &&
                        o->y < m->y + m->want_h && m->y < o->y + o->want_h)
                {
                    m->lx = o->lx + o->lw;
                }
                if (o->y + o->want_h == m->y &&
                        o->x < m->x + m->want_w && m->x < o->x + o->want_w)
                {
                    m->ly = o->ly + o->lh;
                }
            }
        }
    }
}

/* the first n outputs on, placed, sized and scaled as the layout has them;
   the rest off */
static int
wlr_set_layout(void *a, const struct wla_monitor *lay, int n)
{
    struct wlr *b = a;
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        struct wlr_mon *m = b->mons + i;

        m->enabled = i < n;
        if (m->enabled)
        {
            m->x = lay[i].x;
            m->y = lay[i].y;
            m->want_w = lay[i].width;
            m->want_h = lay[i].height;
            m->scale = lay[i].scale >= 100 && lay[i].scale <= 500
                       ? lay[i].scale : 100;
        }
    }
    b->active = n < b->num_mons ? n : b->num_mons;
    layout_logical(b, b->active);
    return layout_apply(b);
}


/*****************************************************************************/
static void
registry_global(void *data, struct wl_registry *reg, uint32_t name,
                const char *iface, uint32_t version)
{
    struct wlr *b = data;

    if (strcmp(iface, wl_output_interface.name) == 0 && version >= 4)
    {
        /* its name event attaches it to its monitor */
        struct output_ref *ref = g_new0(struct output_ref, 1);

        ref->b = b;
        ref->global = name;
        ref->output = wl_registry_bind(reg, name, &wl_output_interface, 4);
        wl_output_add_listener(ref->output, &g_output_listener, ref);
    }
    else if (strcmp(iface, wl_shm_interface.name) == 0)
    {
        b->shm = wl_registry_bind(reg, name, &wl_shm_interface, 1);
    }
    else if (strcmp(iface, wl_seat_interface.name) == 0 && b->seat == NULL)
    {
        b->seat = wl_registry_bind(reg, name, &wl_seat_interface, 1);
    }
    else if (strcmp(iface,
                    ext_output_image_capture_source_manager_v1_interface.name) == 0)
    {
        b->source_mgr = wl_registry_bind(
                            reg, name,
                            &ext_output_image_capture_source_manager_v1_interface, 1);
    }
    else if (strcmp(iface,
                    ext_image_copy_capture_manager_v1_interface.name) == 0)
    {
        b->copy_mgr = wl_registry_bind(
                          reg, name, &ext_image_copy_capture_manager_v1_interface, 1);
    }
    else if (strcmp(iface, zwp_linux_dmabuf_v1_interface.name) == 0 &&
             version >= 3)
    {
        b->dmabuf = wl_registry_bind(reg, name,
                                     &zwp_linux_dmabuf_v1_interface, 3);
    }
    else if (strcmp(iface,
                    zwlr_virtual_pointer_manager_v1_interface.name) == 0)
    {
        b->vptr_mgr = wl_registry_bind(
                          reg, name, &zwlr_virtual_pointer_manager_v1_interface, 1);
    }
    else if (strcmp(iface, zwlr_output_manager_v1_interface.name) == 0)
    {
        b->om_mgr = wl_registry_bind(reg, name,
                                     &zwlr_output_manager_v1_interface,
                                     version >= 4 ? 4 : version);
        zwlr_output_manager_v1_add_listener(b->om_mgr,
                                            &g_om_manager_listener, b);
    }
    else if (strcmp(iface,
                    zwp_virtual_keyboard_manager_v1_interface.name) == 0)
    {
        b->vkbd_mgr = wl_registry_bind(
                          reg, name, &zwp_virtual_keyboard_manager_v1_interface, 1);
    }
}

static void
registry_global_remove(void *data, struct wl_registry *reg, uint32_t name)
{
    struct wlr *b = data;
    int i;

    /* an output was disabled: its wl_output is gone */
    for (i = 0; i < b->num_mons; i++)
    {
        if (b->mons[i].output != NULL && b->mons[i].output_global == name)
        {
            wl_output_release(b->mons[i].output);
            b->mons[i].output = NULL;
        }
    }
}

static const struct wl_registry_listener g_registry_listener =
{
    registry_global, registry_global_remove
};

/*****************************************************************************/
/* capture session (data: the monitor) */

static void
session_buffer_size(void *data,
                    struct ext_image_copy_capture_session_v1 *session,
                    uint32_t width, uint32_t height)
{
    struct wlr_mon *m = data;

    m->width = width;
    m->height = height;
}

static void
session_shm_format(void *data,
                   struct ext_image_copy_capture_session_v1 *session,
                   uint32_t format)
{
    struct wlr_mon *m = data;

    /* either byte order; GLES2 renderers read back XBGR8888 only */
    if (format == WL_SHM_FORMAT_XRGB8888 ||
            (format == WL_SHM_FORMAT_XBGR8888 && m->shm_format == 0))
    {
        m->shm_format = format;
    }
}

static void
session_dmabuf_device(void *data,
                      struct ext_image_copy_capture_session_v1 *session,
                      struct wl_array *device)
{
}

static void
session_dmabuf_format(void *data,
                      struct ext_image_copy_capture_session_v1 *session,
                      uint32_t format, struct wl_array *modifiers)
{
    struct wlr_mon *m = data;
    uint64_t *mod;

    if (format != DRM_FORMAT_XRGB8888)
    {
        return;
    }
    m->have_xrgb = 1;
    free(m->mods);
    m->mods = malloc(modifiers->size + sizeof(uint64_t));
    m->num_mods = 0;
    if (m->mods == NULL)
    {
        /* no modifiers: nothing allocates, and capture_start says so */
        LOG(LOG_LEVEL_ERROR, "monitor %d: out of memory for modifiers",
            m->index);
        return;
    }
    wl_array_for_each(mod, modifiers)
    {
        m->mods[m->num_mods++] = *mod;
    }
}

static void
session_done(void *data, struct ext_image_copy_capture_session_v1 *session)
{
    struct wlr_mon *m = data;

    m->constraints_done = 1;
    /* new constraints for a running capture: the output changed size */
    if (m->alloc_w > 0 &&
            (m->width != m->alloc_w || m->height != m->alloc_h))
    {
        m->constraints_changed = 1;
    }
}

static void
session_stopped(void *data, struct ext_image_copy_capture_session_v1 *session)
{
    struct wlr_mon *m = data;

    m->stopped = 1;
}

static const struct ext_image_copy_capture_session_v1_listener
    g_session_listener =
{
    session_buffer_size, session_shm_format, session_dmabuf_device,
    session_dmabuf_format, session_done, session_stopped
};

/*****************************************************************************/
static void
frame_transform(void *data, struct ext_image_copy_capture_frame_v1 *frame,
                uint32_t transform)
{
}

static void
frame_damage(void *data, struct ext_image_copy_capture_frame_v1 *frame,
             int32_t x, int32_t y, int32_t width, int32_t height)
{
    struct wlr_mon *m = data;
    struct xh_rect *r;

    if (m->num_rects >= MAX_RECTS)
    {
        m->num_rects = 1;
        m->rects[0].x = 0;
        m->rects[0].y = 0;
        m->rects[0].w = m->width;
        m->rects[0].h = m->height;
        return;
    }
    r = m->rects + m->num_rects++;
    r->x = x;
    r->y = y;
    r->w = width;
    r->h = height;
}

static void
frame_presentation_time(void *data,
                        struct ext_image_copy_capture_frame_v1 *frame,
                        uint32_t hi, uint32_t lo, uint32_t nsec)
{
}

static void
frame_ready(void *data, struct ext_image_copy_capture_frame_v1 *frame)
{
    struct wlr_mon *m = data;

    m->frame_state = 2;
}

static void
frame_failed(void *data, struct ext_image_copy_capture_frame_v1 *frame,
             uint32_t reason)
{
    struct wlr_mon *m = data;

    LOG(LOG_LEVEL_WARNING, "monitor %d: capture frame failed, reason %u",
        m->index, reason);
    m->frame_state = 3;
    if (reason == EXT_IMAGE_COPY_CAPTURE_FRAME_V1_FAILURE_REASON_BUFFER_CONSTRAINTS)
    {
        m->constraints_changed = 1;
    }
}

static const struct ext_image_copy_capture_frame_v1_listener g_frame_listener =
{
    frame_transform, frame_damage, frame_presentation_time,
    frame_ready, frame_failed
};

/*****************************************************************************/
/* One capture buffer. GPU path: a single-plane XRGB8888 dma-buf, shared by
   the compositor (wl_buffer) and the helper (EGLImage); tiled modifiers
   first, as they capture faster than LINEAR. CPU path: shared memory. */
static int
alloc_buf(struct wlr_mon *m, struct buf *bf, int index)
{
    static const uint64_t pref[] =
    {
        I915_FORMAT_MOD_Y_TILED, I915_FORMAT_MOD_X_TILED, DRM_FORMAT_MOD_LINEAR
    };
    struct wlr *b = m->b;
    struct zwp_linux_buffer_params_v1 *params;
    uint64_t mod;
    uint32_t stride;
    uint32_t offset;
    int p;
    int i;

    if (b->wl_shm)
    {
        /* CPU path: the compositor copies into shared memory we read */
        struct wl_shm_pool *pool;
        int fd;

        bf->shm_stride = m->width * 4;
        bf->shm_bytes = (size_t) bf->shm_stride * m->height;
        fd = memfd_create("wlxrdp-capture", MFD_CLOEXEC);
        if (fd < 0 || ftruncate(fd, bf->shm_bytes) != 0)
        {
            if (fd >= 0)
            {
                close(fd);
            }
            return 1;
        }
        bf->shm = mmap(NULL, bf->shm_bytes, PROT_READ | PROT_WRITE,
                       MAP_SHARED, fd, 0);
        if (bf->shm == MAP_FAILED)
        {
            bf->shm = NULL;
            close(fd);
            return 1;
        }
        pool = wl_shm_create_pool(b->shm, fd, bf->shm_bytes);
        bf->wl_buffer = wl_shm_pool_create_buffer(pool, 0, m->width,
                        m->height, bf->shm_stride, m->shm_format);
        wl_shm_pool_destroy(pool);
        close(fd);
        LOG(LOG_LEVEL_INFO, "monitor %d buffer %d: %dx%d shm (CPU path)",
            m->index, index, m->width, m->height);
        return 0;
    }

    bf->bo = NULL;
    /* preferred modifiers in order, then anything else offered */
    for (p = 0; p <= (int) (sizeof(pref) / sizeof(pref[0])) &&
            bf->bo == NULL; p++)
    {
        for (i = 0; i < m->num_mods && bf->bo == NULL; i++)
        {
            if (m->mods[i] == DRM_FORMAT_MOD_INVALID)
            {
                continue;
            }
            if (p < (int) (sizeof(pref) / sizeof(pref[0])) &&
                    m->mods[i] != pref[p])
            {
                continue;
            }
            bf->bo = gbm_bo_create_with_modifiers2(b->gbm, m->width,
                                                   m->height,
                                                   DRM_FORMAT_XRGB8888,
                                                   m->mods + i, 1,
                                                   GBM_BO_USE_RENDERING);
            if (bf->bo != NULL && gbm_bo_get_plane_count(bf->bo) != 1)
            {
                gbm_bo_destroy(bf->bo);
                bf->bo = NULL;
            }
        }
    }
    if (bf->bo == NULL)
    {
        LOG(LOG_LEVEL_ERROR, "no single-plane XRGB8888 modifier allocates");
        return 1;
    }
    mod = gbm_bo_get_modifier(bf->bo);
    stride = gbm_bo_get_stride_for_plane(bf->bo, 0);
    offset = gbm_bo_get_offset(bf->bo, 0);
    bf->fd = gbm_bo_get_fd_for_plane(bf->bo, 0);
    if (bf->fd < 0)
    {
        /* free_buf() releases the buffer object */
        LOG(LOG_LEVEL_ERROR, "monitor %d buffer %d: no dma-buf fd for the "
            "buffer object", m->index, index);
        return 1;
    }
    LOG(LOG_LEVEL_INFO, "monitor %d buffer %d: %dx%d modifier 0x%016llx",
        m->index, index, m->width, m->height, (unsigned long long) mod);

    params = zwp_linux_dmabuf_v1_create_params(b->dmabuf);
    zwp_linux_buffer_params_v1_add(params, bf->fd, 0, offset, stride,
                                   mod >> 32, mod & 0xffffffff);
    bf->wl_buffer = zwp_linux_buffer_params_v1_create_immed(
                        params, m->width, m->height, DRM_FORMAT_XRGB8888, 0);
    zwp_linux_buffer_params_v1_destroy(params);
    bf->stride = stride;
    bf->offset = offset;
    bf->modifier = mod;
    return 0;
}

/*****************************************************************************/
static void
free_buf(struct buf *bf)
{
    if (bf->shm != NULL)
    {
        munmap(bf->shm, bf->shm_bytes);
        bf->shm = NULL;
    }
    if (bf->wl_buffer != NULL)
    {
        wl_buffer_destroy(bf->wl_buffer);
        bf->wl_buffer = NULL;
    }
    if (bf->bo != NULL)
    {
        gbm_bo_destroy(bf->bo);
        bf->bo = NULL;
    }
    if (bf->fd >= 0)
    {
        close(bf->fd);
        bf->fd = -1;
    }
}

/*****************************************************************************/
/* the wlroots adapter: capture a frame the core wants, into a buffer the
   core does not hold, when the session can take a request */
static void
request_frame(struct wlr_mon *m)
{
    int index;

    if (!m->wanted || m->session == NULL || m->frame != NULL ||
            m->stopped || m->constraints_changed)
    {
        return;
    }
    for (index = 0; index < NUM_BUFS && m->bufs[index].held; index++)
    {
    }
    if (index == NUM_BUFS)
    {
        return; /* all held: a release retries */
    }
    m->cur = index;
    m->num_rects = 0;
    m->frame_state = 1;
    m->request_ms = now_ms32();
    m->frame = ext_image_copy_capture_session_v1_create_frame(m->session);
    ext_image_copy_capture_frame_v1_add_listener(m->frame, &g_frame_listener,
            m);
    ext_image_copy_capture_frame_v1_attach_buffer(m->frame,
            m->bufs[index].wl_buffer);
    /* whole buffer stale: the compositor copies the full frame, so each
       buffer is complete (AVC444's aux pass needs that) */
    ext_image_copy_capture_frame_v1_damage_buffer(m->frame, 0, 0,
            m->width, m->height);
    ext_image_copy_capture_frame_v1_capture(m->frame);
}


/*****************************************************************************/
/* cursor */

/* The cursor the pointer is on (NULL: none). */
static struct cursor *
cursor_active(struct wlr *b)
{
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        struct cursor *c = &b->mons[i].cur_ptr;

        if (b->mons[i].session != NULL && c->entered)
        {
            return c;
        }
    }
    return NULL;
}


static void
cursor_enter(void *data, struct ext_image_copy_capture_cursor_session_v1 *cs)
{
    struct wlr_mon *m = data;

    m->cur_ptr.entered = 1;
    m->b->cursor_dirty = 1;
}

static void
cursor_leave(void *data, struct ext_image_copy_capture_cursor_session_v1 *cs)
{
    struct wlr_mon *m = data;

    m->cur_ptr.entered = 0;
    m->b->cursor_dirty = 1;
}

static void
cursor_position(void *data,
                struct ext_image_copy_capture_cursor_session_v1 *cs,
                int32_t x, int32_t y)
{
}

static void
cursor_hotspot(void *data, struct ext_image_copy_capture_cursor_session_v1 *cs,
               int32_t x, int32_t y)
{
    struct wlr_mon *m = data;

    m->cur_ptr.hot_x = x;
    m->cur_ptr.hot_y = y;
    m->cur_ptr.hot_pending = 1;
    m->cur_ptr.hot_ms = now_ms32();
}

static const struct ext_image_copy_capture_cursor_session_v1_listener
    g_cursor_listener =
{
    cursor_enter, cursor_leave, cursor_position, cursor_hotspot
};

static void
csession_buffer_size(void *data,
                     struct ext_image_copy_capture_session_v1 *session,
                     uint32_t width, uint32_t height)
{
    struct wlr_mon *m = data;

    m->cur_ptr.width = width;
    m->cur_ptr.height = height;
}

static void
csession_shm_format(void *data,
                    struct ext_image_copy_capture_session_v1 *session,
                    uint32_t format)
{
    struct wlr_mon *m = data;

    if (format == WL_SHM_FORMAT_ARGB8888)
    {
        m->cur_ptr.have_argb = 1;
    }
}

static void
csession_dmabuf_device(void *data,
                       struct ext_image_copy_capture_session_v1 *session,
                       struct wl_array *device)
{
}

static void
csession_dmabuf_format(void *data,
                       struct ext_image_copy_capture_session_v1 *session,
                       uint32_t format, struct wl_array *modifiers)
{
}

static void
csession_done(void *data, struct ext_image_copy_capture_session_v1 *session)
{
    struct wlr_mon *m = data;

    m->cur_ptr.constraints_done = 1;
}

static void
csession_stopped(void *data, struct ext_image_copy_capture_session_v1 *session)
{
    struct wlr_mon *m = data;

    m->cur_ptr.stopped = 1;
}

static const struct ext_image_copy_capture_session_v1_listener
    g_csession_listener =
{
    csession_buffer_size, csession_shm_format, csession_dmabuf_device,
    csession_dmabuf_format, csession_done, csession_stopped
};

static void
cframe_transform(void *data, struct ext_image_copy_capture_frame_v1 *frame,
                 uint32_t transform)
{
}

static void
cframe_damage(void *data, struct ext_image_copy_capture_frame_v1 *frame,
              int32_t x, int32_t y, int32_t width, int32_t height)
{
}

static void
cframe_presentation_time(void *data,
                         struct ext_image_copy_capture_frame_v1 *frame,
                         uint32_t hi, uint32_t lo, uint32_t nsec)
{
}

static void
cframe_ready(void *data, struct ext_image_copy_capture_frame_v1 *frame)
{
    struct wlr_mon *m = data;

    m->cur_ptr.frame_state = 2;
}

static void
cframe_failed(void *data, struct ext_image_copy_capture_frame_v1 *frame,
              uint32_t reason)
{
    struct wlr_mon *m = data;

    m->cur_ptr.frame_state = 3;
    LOG(LOG_LEVEL_DEBUG, "cursor frame failed, reason %u", reason);
}

static const struct ext_image_copy_capture_frame_v1_listener
    g_cframe_listener =
{
    cframe_transform, cframe_damage, cframe_presentation_time,
    cframe_ready, cframe_failed
};

/* (re)allocate the shm buffer to the current constraints */
static int
cursor_alloc(struct wlr_mon *m)
{
    struct cursor *c = &m->cur_ptr;
    struct wl_shm_pool *pool;
    int bytes;
    int fd;

    if (c->buffer != NULL)
    {
        wl_buffer_destroy(c->buffer);
        munmap(c->data, c->buf_w * c->buf_h * 4);
        c->buffer = NULL;
    }
    if (c->width <= 0 || c->height <= 0 || !c->have_argb)
    {
        return 1;
    }
    bytes = c->width * c->height * 4;
    fd = memfd_create("wlxrdp-cursor", MFD_CLOEXEC);
    if (fd < 0 || ftruncate(fd, bytes) != 0)
    {
        if (fd >= 0)
        {
            close(fd);
        }
        return 1;
    }
    c->data = mmap(NULL, bytes, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (c->data == MAP_FAILED)
    {
        close(fd);
        return 1;
    }
    pool = wl_shm_create_pool(m->b->shm, fd, bytes);
    c->buffer = wl_shm_pool_create_buffer(pool, 0, c->width, c->height,
                                          c->width * 4,
                                          WL_SHM_FORMAT_ARGB8888);
    wl_shm_pool_destroy(pool);
    close(fd);
    c->buf_w = c->width;
    c->buf_h = c->height;
    return 0;
}

static void
cursor_request(struct wlr_mon *m)
{
    struct cursor *c = &m->cur_ptr;

    if (c->session == NULL || c->frame != NULL || c->stopped)
    {
        return;
    }
    if (c->buffer == NULL || c->buf_w != c->width || c->buf_h != c->height)
    {
        if (cursor_alloc(m) != 0)
        {
            return;
        }
    }
    c->frame_state = 1;
    c->frame = ext_image_copy_capture_session_v1_create_frame(c->session);
    ext_image_copy_capture_frame_v1_add_listener(c->frame, &g_cframe_listener,
            m);
    ext_image_copy_capture_frame_v1_attach_buffer(c->frame, c->buffer);
    ext_image_copy_capture_frame_v1_damage_buffer(c->frame, 0, 0,
            c->buf_w, c->buf_h);
    ext_image_copy_capture_frame_v1_capture(c->frame);
}

/* a cursor frame completed: keep a copy, mark it for sending */
static void
cursor_frame_done(struct wlr_mon *m)
{
    struct cursor *c = &m->cur_ptr;
    int state = c->frame_state;

    ext_image_copy_capture_frame_v1_destroy(c->frame);
    c->frame = NULL;
    c->frame_state = 0;
    if (state != 2)
    {
        return; /* failed (e.g. new constraints): the next request retries */
    }
    free(c->image);
    c->image = malloc(c->buf_w * c->buf_h * 4);
    if (c->image == NULL)
    {
        return;
    }
    memcpy(c->image, c->data, c->buf_w * c->buf_h * 4);
    c->have_image = 1;
    c->hot_pending = 0; /* the image that goes with the new hotspot */
    m->b->cursor_dirty = 1;
}

/* this output's cursor session, following the virtual pointer */
static void
cursor_start(struct wlr_mon *m)
{
    struct wlr *b = m->b;
    struct cursor *c = &m->cur_ptr;
    struct ext_image_capture_source_v1 *source;

    if (b->pointer == NULL || b->shm == NULL)
    {
        return;
    }
    memset(c, 0, sizeof(*c));
    source = ext_output_image_capture_source_manager_v1_create_source(
                 b->source_mgr, m->output);
    c->csession = ext_image_copy_capture_manager_v1_create_pointer_cursor_session(
                      b->copy_mgr, source, b->pointer);
    ext_image_capture_source_v1_destroy(source);
    ext_image_copy_capture_cursor_session_v1_add_listener(c->csession,
            &g_cursor_listener, m);
    c->session = ext_image_copy_capture_cursor_session_v1_get_capture_session(
                     c->csession);
    ext_image_copy_capture_session_v1_add_listener(c->session,
            &g_csession_listener, m);
    while (!c->constraints_done && !c->stopped)
    {
        if (wl_display_dispatch(b->display) < 0)
        {
            return;
        }
    }
    if (c->stopped || !c->have_argb)
    {
        LOG(LOG_LEVEL_WARNING, "monitor %d: no cursor capture", m->index);
        return;
    }
    cursor_request(m);
}

static void
cursor_stop(struct wlr_mon *m)
{
    struct cursor *c = &m->cur_ptr;

    if (c->frame != NULL)
    {
        ext_image_copy_capture_frame_v1_destroy(c->frame);
    }
    if (c->session != NULL)
    {
        ext_image_copy_capture_session_v1_destroy(c->session);
    }
    if (c->csession != NULL)
    {
        ext_image_copy_capture_cursor_session_v1_destroy(c->csession);
    }
    if (c->buffer != NULL)
    {
        wl_buffer_destroy(c->buffer);
        munmap(c->data, c->buf_w * c->buf_h * 4);
    }
    free(c->image);
    memset(c, 0, sizeof(*c));
    m->b->cursor_dirty = 1;
}

/* A hotspot change waits this long for its image: labwc sends the new
   hotspot, then (for a new shape) the new image; the client must never get
   the new hotspot on the old shape. */
#define HOT_HOLD_MS 50

/* After Wayland events: finished cursor frames, expired hotspot holds, and
   the active output's cursor reported to the core when it changed. */
static void
wlr_cursor_dispatch(struct wlr *b)
{
    int held = 0;
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        struct wlr_mon *m = b->mons + i;
        struct cursor *c = &m->cur_ptr;

        if (c->frame != NULL && c->frame_state >= 2)
        {
            cursor_frame_done(m);
            cursor_request(m);
        }
        if (c->hot_pending && now_ms32() - c->hot_ms >= HOT_HOLD_MS)
        {
            /* hotspot-only change: no new image is coming */
            c->hot_pending = 0;
            b->cursor_dirty = 1;
        }
        held |= c->hot_pending;
    }
    if (b->cursor_dirty && !held)
    {
        struct cursor *c = cursor_active(b);

        b->cursor_dirty = 0;
        if (c != NULL && c->have_image)
        {
            b->ev->cursor(b->core, c->image, c->buf_w, c->buf_h, c->hot_x,
                          c->hot_y);
        }
        else
        {
            b->ev->cursor(b->core, NULL, 0, 0, 0, 0);
        }
    }
}

/* when the cursor next needs a look (ms), -1: not before an event */
static int
wlr_cursor_timeout(struct wlr *b)
{
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        if (b->mons[i].cur_ptr.hot_pending)
        {
            return HOT_HOLD_MS;
        }
    }
    return -1;
}

/*****************************************************************************/
/* The wlroots adapter's input: the virtual keyboard and pointer
   protocols. */

static void
wlr_key(void *a, int evdev, int down)
{
    struct wlr *b = a;

    if (b->vkbd != NULL)
    {
        zwp_virtual_keyboard_v1_key(b->vkbd, now_ms32(), evdev,
                                    down ? WL_KEYBOARD_KEY_STATE_PRESSED
                                    : WL_KEYBOARD_KEY_STATE_RELEASED);
    }
}

static void
wlr_modifiers(void *a, uint32_t depressed, uint32_t latched,
              uint32_t locked, uint32_t group)
{
    struct wlr *b = a;

    if (b->vkbd != NULL)
    {
        zwp_virtual_keyboard_v1_modifiers(b->vkbd, depressed, latched, locked,
                                          group);
    }
}

/* the keymap goes to the compositor as a memfd */
static int
wlr_keymap(void *a, const char *text)
{
    struct wlr *b = a;
    size_t len = strlen(text) + 1;
    int rv = 1;
    int fd;
    void *p;

    if (b->vkbd == NULL)
    {
        return 1;
    }
    fd = memfd_create("wlxrdp-keymap", MFD_CLOEXEC);
    if (fd >= 0 && ftruncate(fd, len) == 0)
    {
        p = mmap(NULL, len, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
        if (p != MAP_FAILED)
        {
            memcpy(p, text, len);
            munmap(p, len);
            zwp_virtual_keyboard_v1_keymap(b->vkbd,
                                           WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1,
                                           fd, len);
            rv = 0;
        }
    }
    if (fd >= 0)
    {
        close(fd);
    }
    return rv;
}

static void
wlr_motion(void *a, int x, int y, int width, int height)
{
    struct wlr *b = a;
    struct wlr_mon *m = NULL;
    int64_t best = -1;
    int ext_w = 0;
    int ext_h = 0;
    double lx;
    double ly;
    int i;

    if (b->vptr == NULL)
    {
        return;
    }
    /* the monitor under (x, y) in layout pixels, or the nearest; and the
       logical layout's extent, which the compositor maps absolute
       positions onto */
    for (i = 0; i < b->active; i++)
    {
        struct wlr_mon *o = b->mons + i;
        int64_t dx = x < o->x ? o->x - x : x >= o->x + o->want_w
                     ? x - (o->x + o->want_w - 1) : 0;
        int64_t dy = y < o->y ? o->y - y : y >= o->y + o->want_h
                     ? y - (o->y + o->want_h - 1) : 0;

        if (best < 0 || dx * dx + dy * dy < best)
        {
            best = dx * dx + dy * dy;
            m = o;
        }
        ext_w = o->lx + o->lw > ext_w ? o->lx + o->lw : ext_w;
        ext_h = o->ly + o->lh > ext_h ? o->ly + o->lh : ext_h;
    }
    if (m == NULL || ext_w <= 0 || ext_h <= 0)
    {
        zwlr_virtual_pointer_v1_motion_absolute(b->vptr, now_ms32(), x, y,
                                                width, height);
        zwlr_virtual_pointer_v1_frame(b->vptr);
        return;
    }
    x = x < m->x ? m->x : x >= m->x + m->want_w ? m->x + m->want_w - 1 : x;
    y = y < m->y ? m->y : y >= m->y + m->want_h ? m->y + m->want_h - 1 : y;
    lx = m->lx + (x - m->x) * 100.0 / m->scale;
    ly = m->ly + (y - m->y) * 100.0 / m->scale;
    /* in 1/16ths of a logical pixel, so a scaled monitor keeps every
       client pixel */
    zwlr_virtual_pointer_v1_motion_absolute(
        b->vptr, now_ms32(), (uint32_t) lround(lx * 16),
        (uint32_t) lround(ly * 16), (uint32_t) ext_w * 16,
        (uint32_t) ext_h * 16);
    zwlr_virtual_pointer_v1_frame(b->vptr);
}

static void
wlr_button(void *a, int button, int down)
{
    struct wlr *b = a;

    if (b->vptr != NULL)
    {
        zwlr_virtual_pointer_v1_button(b->vptr, now_ms32(), button,
                                       down ? WL_POINTER_BUTTON_STATE_PRESSED
                                       : WL_POINTER_BUTTON_STATE_RELEASED);
        zwlr_virtual_pointer_v1_frame(b->vptr);
    }
}

static void
wlr_scroll(void *a, enum wla_axis axis, int discrete, double value)
{
    struct wlr *b = a;
    uint32_t wl_axis = axis == WLA_AXIS_HORIZONTAL
                       ? WL_POINTER_AXIS_HORIZONTAL_SCROLL
                       : WL_POINTER_AXIS_VERTICAL_SCROLL;

    if (b->vptr == NULL)
    {
        return;
    }
    /* The source goes after the axis event, as the protocol allows (any
       time before the frame): wlroots applies it to the axis last named,
       so sent first it lands on the other axis after an axis change. */
    if (discrete != 0)
    {
        zwlr_virtual_pointer_v1_axis_discrete(b->vptr, now_ms32(), wl_axis,
                                              wl_fixed_from_double(value),
                                              discrete);
        zwlr_virtual_pointer_v1_axis_source(b->vptr,
                                            WL_POINTER_AXIS_SOURCE_WHEEL);
    }
    else
    {
        zwlr_virtual_pointer_v1_axis(b->vptr, now_ms32(), wl_axis,
                                     wl_fixed_from_double(value));
        zwlr_virtual_pointer_v1_axis_source(b->vptr,
                                            WL_POINTER_AXIS_SOURCE_CONTINUOUS);
    }
    zwlr_virtual_pointer_v1_frame(b->vptr);
}



/*****************************************************************************/
/* capture lifecycle */

static int
capture_start(struct wlr_mon *m)
{
    struct wlr *b = m->b;
    struct ext_image_capture_source_v1 *source;
    struct wla_buffer wb[NUM_BUFS];
    int i;

    if (m->output == NULL)
    {
        LOG(LOG_LEVEL_ERROR, "monitor %d (%s): no output to capture",
            m->index, m->name);
        return 1;
    }
    m->constraints_done = 0;
    m->stopped = 0;
    m->have_xrgb = 0;
    m->shm_format = 0;
    source = ext_output_image_capture_source_manager_v1_create_source(
                 b->source_mgr, m->output);
    m->session = ext_image_copy_capture_manager_v1_create_session(
                     b->copy_mgr, source, 0 /* cursor not painted */);
    ext_image_capture_source_v1_destroy(source);
    ext_image_copy_capture_session_v1_add_listener(m->session,
            &g_session_listener, m);
    while (!m->constraints_done && !m->stopped)
    {
        if (wl_display_dispatch(b->display) < 0)
        {
            return 1;
        }
    }
    if (m->stopped || (b->wl_shm ? m->shm_format == 0 : !m->have_xrgb))
    {
        LOG(LOG_LEVEL_ERROR, "monitor %d: capture session unusable",
            m->index);
        return 1;
    }
    LOG(LOG_LEVEL_INFO, "monitor %d: capturing %s at %dx%d", m->index,
        m->name, m->width, m->height);
    for (i = 0; i < NUM_BUFS; i++)
    {
        struct wla_buffer *w = wb + i;

        if (alloc_buf(m, m->bufs + i, i) != 0)
        {
            return 1;
        }
        m->bufs[i].held = 0;
        memset(w, 0, sizeof(*w));
        w->width = m->width;
        w->height = m->height;
        w->fourcc = !b->wl_shm || m->shm_format == WL_SHM_FORMAT_XRGB8888
                    ? DRM_FORMAT_XRGB8888 : DRM_FORMAT_XBGR8888;
        w->fd = m->bufs[i].fd;
        w->stride = m->bufs[i].stride;
        w->offset = m->bufs[i].offset;
        w->modifier = m->bufs[i].modifier;
        w->shm = m->bufs[i].shm;
        w->shm_stride = m->bufs[i].shm_stride;
    }
    b->ev->buffers(b->core, m->index, NUM_BUFS, wb);
    m->last_ready = -1;
    m->alloc_w = m->width;
    m->alloc_h = m->height;
    m->constraints_changed = 0;
    m->capture_ms = now_ms32();
    m->wanted = 0;
    cursor_start(m);
    return 0;
}

/*****************************************************************************/
static void
capture_stop(struct wlr_mon *m)
{
    int i;

    cursor_stop(m);
    if (m->frame != NULL)
    {
        ext_image_copy_capture_frame_v1_destroy(m->frame);
        m->frame = NULL;
    }
    if (m->session != NULL)
    {
        ext_image_copy_capture_session_v1_destroy(m->session);
        m->session = NULL;
    }
    for (i = 0; i < NUM_BUFS; i++)
    {
        free_buf(m->bufs + i);
    }
    m->last_ready = -1;
    m->frame_state = 0;
    m->alloc_w = 0;
    m->alloc_h = 0;
    m->wanted = 0;
    m->b->ev->buffers(m->b->core, m->index, 0, NULL);
}

/*****************************************************************************/
/* Capture every monitor in the layout. */
static int
capture_start_all(struct wlr *b)
{
    int rv = 0;
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        b->mons[i].retries = 0;
        if (b->mons[i].enabled && capture_start(b->mons + i) != 0)
        {
            capture_stop(b->mons + i);
            rv = 1;
        }
    }
    return rv;
}

/*****************************************************************************/
static void
capture_stop_all(struct wlr *b)
{
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        capture_stop(b->mons + i);
    }
    wl_display_roundtrip(b->display);
}

/*****************************************************************************/
/* One monitor's capture again, e.g. after its output changed size. */
static void
capture_restart(struct wlr_mon *m)
{
    capture_stop(m);
    wl_display_roundtrip(m->b->display);
    if (capture_start(m) != 0)
    {
        /* nothing captured: wlr_capture_dispatch retries it */
        capture_stop(m);
        m->retries++;
        m->retry_ms = now_ms32();
        LOG(LOG_LEVEL_WARNING, "monitor %d: capture did not restart "
            "(attempt %d of %d)", m->index, m->retries, CAPTURE_RETRIES);
        return;
    }
    m->retries = 0; /* the core resends the helper's batch */
}

/*****************************************************************************/
/* a capture completed: hand it to the core */
static void
on_frame_done(struct wlr_mon *m)
{
    int state = m->frame_state;

    ext_image_copy_capture_frame_v1_destroy(m->frame);
    m->frame = NULL;
    m->frame_state = 0;
    if (state == 3)
    {
        return; /* failed: the next request retries */
    }
    m->last_ready = m->cur;
    m->bufs[m->cur].held = 1;
    m->wanted = 0;
    m->b->ev->frame(m->b->core, m->index, m->cur, m->rects, m->num_rects);
}

/*****************************************************************************/
/* The wlroots adapter's capture ops (wla_ops) and its part of the loop */

static int
wlr_start(void *a, enum wla_mode mode)
{
    struct wlr *b = a;

    b->wl_shm = mode == WLA_SHM;
    b->capturing = 1;
    return capture_start_all(b);
}

static void
wlr_stop(void *a)
{
    struct wlr *b = a;

    b->capturing = 0;
    capture_stop_all(b);
}

static void
wlr_want_frame(void *a, int mon)
{
    struct wlr *b = a;

    if (mon >= 0 && mon < b->num_mons)
    {
        b->mons[mon].wanted = 1;
        request_frame(b->mons + mon);
    }
}

static void
wlr_release(void *a, int mon, int buf)
{
    struct wlr *b = a;

    if (mon >= 0 && mon < b->num_mons && buf >= 0 && buf < NUM_BUFS)
    {
        b->mons[mon].bufs[buf].held = 0;
        request_frame(b->mons + mon); /* one may be waiting for a buffer */
    }
}

/* After Wayland events: finished captures, and the capture watchdogs */
static void
wlr_capture_dispatch(struct wlr *b)
{
    int i;

    for (i = 0; i < b->num_mons; i++)
    {
        struct wlr_mon *m = b->mons + i;

        if (m->frame != NULL && m->frame_state >= 2)
        {
            on_frame_done(m);
        }
        if (m->session == NULL)
        {
            if (b->capturing && m->enabled && m->retries > 0 &&
                    now_ms32() - m->retry_ms >= CAPTURE_RETRY_MS)
            {
                if (m->retries >= CAPTURE_RETRIES)
                {
                    b->ev->lost(b->core, "a monitor's capture could not be "
                                "restarted");
                    return;
                }
                capture_restart(m);
                m->wanted = 1;
                request_frame(m);
            }
            continue;
        }
        if (m->stopped)
        {
            LOG(LOG_LEVEL_WARNING, "monitor %d: capture session "
                "stopped, restarting", m->index);
            capture_restart(m);
        }
        else if (m->constraints_changed)
        {
            /* the compositor changed the output's size itself (not a
               client resize): capture at the new size. xrdp's surface is
               still the client's size, so this only keeps the session
               alive until the client resizes. */
            LOG(LOG_LEVEL_WARNING, "monitor %d: capture constraints "
                "changed to %dx%d, restarting capture", m->index,
                m->width, m->height);
            capture_restart(m);
        }
        else if (m->last_ready < 0 && m->frame != NULL &&
                 now_ms32() - m->request_ms >= FIRST_FRAME_MS)
        {
            /* a new session delivers its first frame at once: this one is
               stuck (no clock runs while no frame is wanted) */
            LOG(LOG_LEVEL_WARNING, "monitor %d: no first frame %d ms after "
                "asking, restarting capture", m->index, FIRST_FRAME_MS);
            capture_restart(m);
            m->wanted = 1; /* the frame the stuck session owed */
        }
        request_frame(m); /* a failed frame, or a restart, retries */
    }
}


/*****************************************************************************/
/* HEADLESS-2 after HEADLESS-1, and HEADLESS-10 after HEADLESS-9 */
static int
mon_cmp(const void *a, const void *b)
{
    const char *na = ((const struct wlr_mon *) a)->name;
    const char *nb = ((const struct wlr_mon *) b)->name;
    size_t la = strcspn(na, "0123456789");
    size_t lb = strcspn(nb, "0123456789");
    int c = strncmp(na, nb, la < lb ? la : lb);

    if (c != 0 || la != lb)
    {
        return c != 0 ? c : (int) la - (int) lb;
    }
    return atoi(na + la) - atoi(nb + lb);
}

/*****************************************************************************/
/* connect, and check the compositor has what we need */
static void *
wlr_create(const struct wla_events *ev, void *core)
{
    struct wlr *b;
    struct wl_registry *reg;
    const char *drm;
    int i;
    int j;

    b = calloc(1, sizeof(*b));
    if (b == NULL)
    {
        return NULL;
    }
    b->ev = ev;
    b->core = core;
    b->drm_fd = -1;
    for (i = 0; i < MAX_MONS; i++)
    {
        b->mons[i].b = b;
        b->mons[i].last_ready = -1;
        for (j = 0; j < NUM_BUFS; j++)
        {
            b->mons[i].bufs[j].fd = -1;
        }
    }

    b->display = wl_display_connect(NULL);
    if (b->display == NULL)
    {
        LOG(LOG_LEVEL_ERROR, "wlr: cannot connect to the Wayland display");
        free(b);
        return NULL;
    }
    reg = wl_display_get_registry(b->display);
    wl_registry_add_listener(reg, &g_registry_listener, b);
    wl_display_roundtrip(b->display);
    wl_display_roundtrip(b->display); /* heads, output names */
    if (b->num_mons < 1 || b->seat == NULL || b->source_mgr == NULL ||
            b->copy_mgr == NULL || b->dmabuf == NULL || b->vptr_mgr == NULL ||
            b->vkbd_mgr == NULL || b->om_mgr == NULL)
    {
        LOG(LOG_LEVEL_ERROR, "wlr: compositor lacks a required protocol "
            "(output management, seat, ext-image-copy-capture, "
            "linux-dmabuf v3, wlr virtual pointer, virtual keyboard)");
        wlr_destroy(b);
        return NULL;
    }

    drm = getenv("WLXRDP_DRM");
    b->drm_fd = open(drm != NULL ? drm : "/dev/dri/renderD128",
                     O_RDWR | O_CLOEXEC);
    b->gbm = (b->drm_fd >= 0) ? gbm_create_device(b->drm_fd) : NULL;
    if (b->gbm == NULL)
    {
        /* GBM only allocates the capture buffers; encoding is the
           helper's */
        LOG(LOG_LEVEL_ERROR, "wlr: cannot open the render node for GBM");
        wlr_destroy(b);
        return NULL;
    }

    /* monitor i is the i-th output by name. Nothing holds a pointer into
       mons[] yet (listeners find monitors by name), so sorting is safe. */
    qsort(b->mons, b->num_mons, sizeof(b->mons[0]), mon_cmp);
    for (i = 0; i < b->num_mons; i++)
    {
        b->mons[i].index = i;
    }
    LOG(LOG_LEVEL_INFO, "wlr: %d output(s): first %s", b->num_mons,
        b->mons[0].name);
    b->vptr = zwlr_virtual_pointer_manager_v1_create_virtual_pointer(
                  b->vptr_mgr, b->seat);
    b->vkbd = zwp_virtual_keyboard_manager_v1_create_virtual_keyboard(
                  b->vkbd_mgr, b->seat);
    /* the virtual pointer gives the seat a pointer; the cursor sessions
       follow it */
    wl_display_roundtrip(b->display);
    b->pointer = wl_seat_get_pointer(b->seat);
    return b;
}

/*****************************************************************************/
/* wlxrdp is exiting: the compositor frees the rest with the connection */
static void
wlr_destroy(void *a)
{
    struct wlr *b = a;

    if (b == NULL)
    {
        return;
    }
    capture_stop_all(b);
    if (b->display != NULL)
    {
        wl_display_flush(b->display);
        wl_display_disconnect(b->display);
    }
    if (b->gbm != NULL)
    {
        gbm_device_destroy(b->gbm);
    }
    if (b->drm_fd >= 0)
    {
        close(b->drm_fd);
    }
    free(b);
}

/*****************************************************************************/
/* before poll: the display fd, read-prepared; wake for a cursor's hotspot
   hold */
static int
wlr_fds(void *a, struct pollfd *p, int max, int *timeout_ms)
{
    struct wlr *b = a;
    int t;

    if (max < 1)
    {
        return 0;
    }
    while (wl_display_prepare_read(b->display) != 0)
    {
        wl_display_dispatch_pending(b->display);
    }
    wl_display_flush(b->display);
    p[0].fd = wl_display_get_fd(b->display);
    p[0].events = POLLIN;
    p[0].revents = 0;
    t = wlr_cursor_timeout(b);
    if (t >= 0 && (*timeout_ms < 0 || t < *timeout_ms))
    {
        *timeout_ms = t;
    }
    return 1;
}

/*****************************************************************************/
/* after poll (every time wlr_fds was called): read and handle events */
static int
wlr_dispatch(void *a, const struct pollfd *p, int n)
{
    struct wlr *b = a;

    if (n >= 1 && (p[0].revents & POLLIN))
    {
        if (wl_display_read_events(b->display) < 0)
        {
            b->ev->lost(b->core, "Wayland connection lost");
            return -1;
        }
    }
    else
    {
        wl_display_cancel_read(b->display);
    }
    if (n >= 1 && (p[0].revents & (POLLHUP | POLLERR)) &&
            !(p[0].revents & POLLIN))
    {
        b->ev->lost(b->core, "Wayland connection lost");
        return -1;
    }
    if (wl_display_dispatch_pending(b->display) < 0)
    {
        b->ev->lost(b->core, "Wayland connection lost");
        return -1;
    }
    wlr_capture_dispatch(b);
    wlr_cursor_dispatch(b);
    return 0;
}

/*****************************************************************************/
const struct wla_ops wla_wlr =
{
    .name = "wlr",
    .caps = WLA_CAP_SET_KEYMAP | WLA_CAP_CURSOR,
    .create = wlr_create,
    .destroy = wlr_destroy,
    .max_monitors = wlr_max_monitors,
    .set_layout = wlr_set_layout,
    .start = wlr_start,
    .stop = wlr_stop,
    .want_frame = wlr_want_frame,
    .release = wlr_release,
    .keymap = wlr_keymap,
    .key = wlr_key,
    .modifiers = wlr_modifiers,
    .motion = wlr_motion,
    .button = wlr_button,
    .scroll = wlr_scroll,
    .fds = wlr_fds,
    .dispatch = wlr_dispatch
};
